#!/bin/bash

set -e

mysqld --bootstrap << EOF 
CREATE DATABASE IF NOT EXISTS wordpress;
CREATE USER  $SQLUSER@'localhost';
SET PASSWORD FOR  $SQLUSER@'localhost' = PASSWORD($SQLPASS);
GRANT ALL PRIVILEGES ON wordpress.* TO $SQLUSER@'localhost' IDENTIFIED BY $SQLPASS;
GRANT ALL ON wordpress.* to 'jemartel'@'%' IDENTIFIED BY  $SQLPASS;

FLUSH PRIVILEGES;

CREATE USER 'superuser'@'localhost' IDENTIFIED BY $ADMINPASS;
GRANT ALL PRIVILEGES ON *.* TO 'superuser'@'localhost' WITH GRANT OPTION;
FLUSH PRIVILEGES;
CREATE USER 'superuser'@'%' IDENTIFIED BY $ADMINPASS;
GRANT ALL PRIVILEGES ON *.* TO 'superuser'@'%' WITH GRANT OPTION;

FLUSH PRIVILEGES;

ALTER USER 'root'@'localhost' IDENTIFIED BY $SQl_ROOT_PASS;

FLUSH PRIVILEGES;
EOF
 