version: "3"

services:
  mariadb:
    container_name: "mariadb"
    build: 
      context: ./requirements/mariadb/
      args:
        - ROOTPASS=${ROOTPASS}
        - WORDPRESS_DB_USER=${WORDPRESS_DB_USER}
        - WORDPRESS_DB_HOST=${WORDPRESS_DB_HOST}
        - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
        - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}
    restart: unless-stopped
    volumes:
      - ${VOLPATH}/mariadb/:/var/lib/mysql/
    networks:
      - inception
    env_file:
      - .env

  wordpress:
    container_name: "wordpress"
    env_file:
      - .env
    build: 
      context:
        ./requirements/wordpress/
      args:
        - WORDPRESS_DB_USER=${WORDPRESS_DB_USER}

    volumes:
      - ${VOLPATH}/wordpress:/var/www/wordpress/
    restart: unless-stopped
    networks:
      - inception
    depends_on:
      - "mariadb"
  nginx:
    container_name: "nginx"
    build: ./requirements/nginx/
    ports:
      - "443:443"
    volumes:
      - ${VOLPATH}/wordpress:/var/www/wordpress/
    restart: unless-stopped
    networks:
      - inception
    env_file:
      - .env

networks:
  inception:

volumes:
  volume-mariadb:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ${VOLPATH}/mariadb
  volume-wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ${VOLPATH}/wordpress